# Generated by Django 4.1.3 on 2023-03-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('post', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
