# Generated by Django 4.1.3 on 2023-03-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='department',
        ),
    ]
