# Generated by Django 4.1.3 on 2023-03-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_remove_team_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(default='department', max_length=100),
        ),
    ]
