# Generated by Django 4.1.3 on 2023-03-20 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0003_team_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email address')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
