# Generated by Django 4.1.3 on 2023-03-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0004_alter_team_email_alter_team_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='static/images/chaur.jpg', upload_to='static/images'),
        ),
    ]
