# Generated by Django 4.1.7 on 2023-03-30 08:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=200)),
                ('hero_image', models.ImageField(upload_to='static/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('review', models.TextField(blank=True)),
                ('rating', models.FloatField(default=5)),
                ('source', models.CharField(choices=[('Trustpilot', 'Trustpilot'), ('Google', 'Google'), ('Others', 'Others')], max_length=30)),
            ],
        ),
    ]
