# Generated by Django 4.1.3 on 2023-03-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero_Section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliolists',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
