# Generated by Django 4.1.7 on 2023-04-03 08:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAndDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(max_length=500)),
            ],
        ),
    ]
