# Generated by Django 4.1.3 on 2023-03-24 10:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAndDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField(max_length=500)),
            ],
        ),
    ]
