# Generated by Django 4.1.3 on 2023-03-24 10:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='<strong>Name</strong>', max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail_image', models.ImageField(upload_to='static/images')),
                ('title', ckeditor.fields.RichTextField(max_length=200)),
                ('article_content', tinymce.models.HTMLField(max_length=500)),
                ('time_to_read', models.PositiveSmallIntegerField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField(max_length=400)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.authors')),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.articlecategory')),
            ],
        ),
    ]
