# Generated by Django 4.1.3 on 2023-03-19 06:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_article_delete_featuredarticles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_to_read',
            field=models.PositiveSmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
