# Generated by Django 4.1.3 on 2023-03-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.authors'),
        ),
        migrations.AddField(
            model_name='authors',
            name='author_name',
            field=models.CharField(blank=True, help_text='<strong>Name</strong>', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='c_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.articlecategory'),
        ),
    ]
