# Generated by Django 4.1.7 on 2023-04-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(help_text='select service category', on_delete=django.db.models.deletion.CASCADE, to='Services.service'),
        ),
    ]
