# Generated by Django 4.1.3 on 2023-03-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_portfolio_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
