# Generated by Django 4.1.3 on 2023-03-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_alter_portfolio_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sercategory',
            old_name='category',
            new_name='name',
        ),
    ]
