# Generated by Django 4.1.3 on 2023-03-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_rename_category_sercategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sercategory',
            old_name='name',
            new_name='category',
        ),
    ]
