# Generated by Django 4.1.3 on 2023-03-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
        ('Hero_Section', '0002_alter_portfoliolists_company'),
        ('Portfolio', '0005_rename_name_sercategory_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SerCategory',
            new_name='PortfolioCategory',
        ),
    ]
